packages:
  # Externals

  # Prfs
  - "source/incremental-merkle-tree2"
  - "source/prfs_circuit_artifact_uri_resolver"
  - "source/prfs_docs_website"
  - "source/prfs_driver_spartan_js"
  - "source/prfs_driver_interface"
  - "source/prfs_circuit_interface"
  - "source/prfs_circuits_circom"
  - "source/prfs_crypto_js"
  - "source/prfs_crypto_deps_js"
  - "source/prfs_entities"
  - "source/prfs_i18n"
  - "source/prfs_env_js"
  - "source/prfs_react_lib"
  - "source/prfs_id_sdk_web"
  - "source/prfs_proof_gen_js"
  - "source/prfs_ts_utils"
  - "source/prfs_api_js"
  - "source/prfs_api_server"
  - "source/prfs_snap"
  - "source/prfs_proof_webapp"
  - "source/prfs_console_webapp"
  - "source/prfs_poll_webapp"
  - "source/prfs_id_webapp"

  # Shy
  - "source/shy_webapp"
  - "source/shy_api_server"
  - "source/shy_docs_website"
