packages:
  # Externals
  - "externals/incremental-merkle-tree"

  # Prfs endpoints
  - "source/prfs_endpoints"

  # Docs
  - "source/docs_website"

  # i18n
  - "source/prfs_i18n"

  # Circuits
  - "source/prfs_circuits_circom"

  # Driver
  - "source/prfs_driver_spartan_js"
  - "source/prfs_driver_interface"

  # Prfs
  - "source/prfs_snap"
  - "source/prfs_crypto_js"
  - "source/prfs_api_js"
  - "source/prfs_api_server"
  - "source/prfs_auth_op_server"
  - "source/prfs_entities"

  # Prfs SDK
  - "source/prfs_sdk_web"
  - "source/prfs_sdk_web_module"

  # Prfs webapps
  - "source/prfs_proof_webapp"
  - "source/prfs_console_webapp"
  - "source/prfs_poll_webapp"

  # Common ui components
  - "source/prfs_react_components"

  # Shy
  - "source/shy_webapp"

  # Prfs identity
  - "source/prfs_id_webapp"
  - "source/prfs_id_sdk_web"

  # Prfs proof gen
  - "source/prfs_proof_gen_js"

  # Prfs embed
  - "source/prfs_embed_webapp"
