packages:
  # Externals
  - "externals/incremental-merkle-tree"

  # Prfs docs website
  - "source/docs_website"

  # Prfs circuits
  - "source/prfs_circuits_circom"

  # Prfs driver
  - "source/prfs_driver_spartan_js"
  - "source/prfs_driver_interface"

  # Prfs
  - "source/prfs_crypto_js"
  - "source/prfs_entities"
  - "source/prfs_i18n"
  - "source/prfs_env_js"
  - "source/prfs_react_lib"
  - "source/prfs_id_sdk_web"
  - "source/prfs_id_sdk_react"
  - "source/prfs_proof_gen_js"
  - "source/prfs_api_js"
  - "source/prfs_api_server"
  - "source/prfs_snap"
  - "source/prfs_proof_interface"

  # Prfs SDK (deprecated)
  - "source/prfs_sdk_web"
  - "source/prfs_sdk_web_module"

  # Prfs webapps
  - "source/prfs_proof_webapp"
  - "source/prfs_console_webapp"
  - "source/prfs_poll_webapp"
  - "source/prfs_id_webapp"
  - "source/prfs_embed_webapp"

  # Shy
  - "source/shy_webapp"
